# Generated by Django 4.0.2 on 2022-06-27 14:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=50)),
                ('subject', models.CharField(default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=350)),
                ('validations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.IntegerField(default=api.models.RandomKey, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
